name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go: ['1.20', '1.21', '1.22']

    steps:
    - id: go
      name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: go build -v .
    
    - name: Test
      run: go test -v -coverprofile=profile.cov .

    - name: Send coverage
      run: bash <(curl -s https://codecov.io/bash) -f profile.cov
